changes a few lines of code in the block code of the if satement with…
daniel-alts/example-nodejs-server-api pull request #1
Opened 2023-08-09 22:35 UTC by Jbsmall17

… conditions:req.url.startsWith('/v1/students/') && req.method === 'PATCH', in the handleRequest function

2023-08-09 22:42 UTC, Jbsmall17 commented
The response of the http PATCH METHOD of the api server built in api.js was meant to return the updated version on the students rather it return the un-updated version of the students array. I have resolved that by applying  splice method on the students array(line 73 of api.js file).

2023-08-14 05:40 UTC, daniel-alts requested changes
Looks good to me. 

Just update the code to ensure that updates are captured for other properties of the students. No need to update the id

2023-08-14 05:40 UTC, daniel-alts commented on api.js
> +        const student = { ...students[studentIndex],id: Math.floor(Math.random() * 10).toString()} //, updates the student information
This only changes the id of the student. What if body of the request contains other details?.

2023-08-14 05:40 UTC, daniel-alts commented on api.js
> +        students.splice(studentIndex,1,student) //removes the oldstudent info and replaced it with updated info
Adding this here fixes the issue. Awesome work on noticing this bug

2023-08-14 11:22 UTC, Jbsmall17 commented
thanks for your review and feedback

2023-08-15 02:08 UTC, merged